//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerData
    {
        public int cid { get; set; }
        public string CustomerType { get; set; }
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public Nullable<decimal> CustomerAmount { get; set; }
    }
}
